### ISSUE TITLE
如何有效烧写firmware？

### ISSUE THREAD

**Issue by BernardXiong** [steward-fu/miyoo#1]
春节前时买过一台，拆机了，对电路进行处理能够把firmware烧写上去，但是装不上外壳了。

如果需要保留USB口烧写（不需要串口了，只USB烧写即可），外壳完好，应该如何比较好？求教 🙏

**Comment by steward-fu** [comment]
你改4it sdcard就可以, 改完, 我在跟你說如何燒錄

**Comment by steward-fu** [comment]
close
