### ISSUE TITLE
bin + img

### ISSUE THREAD

**Issue by ferrdo4** [steward-fu/miyoo#2]
Hi, i was very excited when i find out there is a custom fw for bittboy, but i got sad when i find out i have old rew 1 hw. i had no trouble to do soldering and make sunxi tool work and communicate with bittboy via usb, but i cant find .bin file to write to device and .img to write to sd. do i need to build it up based on your wiki or is there way to get them?
you have done great work from what i saw so far!

**Comment by steward-fu** [comment]
v1 is best one so far, ha ha
yes, build it by yourself is more fun than use built images.
build it and tell me if you suffer from some issues

**Comment by ferrdo4** [comment]
sooo, i build up uboot and kernel, prepared sd card, but for some reason bittboy does seems to be booting up, not sure what i've done wrong :) but i will try to make uart work and see what is going on via console

**Comment by steward-fu** [comment]
do you have modded sdcard with 4bit mode ? 
in order to boot from sdcard,  your sdcard MUST support 4bit mode.

**Comment by ferrdo4** [comment]
yes, i did not and i will do, 
but it seems that issue is even before booting, before LCD lit up, now it does not
right now i am soldering com connector so i can see how far it gets.
i have question am i doing it right to build "boot from SPI flash" uboot for v1 ?
thanks for your help

**Comment by steward-fu** [comment]
since no any information will be sent to COM port, you just need to build uboot for sdcard, not for spi

**Comment by ferrdo4** [comment]
ok i make bittboy work again with stock spi :D 
when i build sd uboot do i need to write somethig to bittboy with fel or just 1024b to sdcard ?
i am doing 4-bit mode right now

**Comment by steward-fu** [comment]
just write to sdcard
